### ISSUE TITLE
open-hackathon-server error

### ISSUE THREAD

**Issue by zsynacl** [msopentechcn/open-hackathon#650]
File "hackathon/open-hackathon/open-hackathon-server/src/hackathon/user/user_manager.py", line 111, in check_user_online_status
    if (self.util.get_now() - users_operation_time[user_id]).minutes > 60]
AttributeError: 'datetime.timedelta' object has no attribute 'minutes'

I'm using python 2.7.6, but I did'n found any documentation about attribute 'minutes' in timedelta object. Maybe it is just a mistake?

**Comment by juniwang** [comment]
Thanks. We will look into it soon

**Comment by zsynacl** [comment]
here goes full log

```
2016-08-15 21:00:00,607 - DEBUG(APScheduler) - Looking for jobs to run
2016-08-15 21:00:00,608 - INFO(Thread-42) - Running job "scheduler_executor (trigger: interval[0:10:00], next run at: 2016-08-16 01:00:00 UTC)" (scheduled at 2016-08-16 01:00:00.600872+00:00)
2016-08-15 21:00:00,609 - DEBUG(Thread-42) - prepare to execute 'user_manager.check_user_online_status' with context: None
2016-08-15 21:00:00,610 - ERROR(Thread-42) - Job "scheduler_executor (trigger: interval[0:10:00], next run at: 2016-08-16 01:10:00 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 108, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "hackathon/open-hackathon/open-hackathon-server/src/hackathon/hackathon_scheduler.py", line 87, in scheduler_executor
    mtd()
  File "hackathon/open-hackathon/open-hackathon-server/src/hackathon/user/user_manager.py", line 111, in check_user_online_status
    if (self.util.get_now() - users_operation_time[user_id]).minutes > 60]
AttributeError: 'datetime.timedelta' object has no attribute 'minutes'
2016-08-15 21:00:00,610 - DEBUG(Thread-42) - The job crashed :(
2016-08-15 21:00:00,610 - DEBUG(APScheduler) - Next wakeup is due at 2016-08-16 01:10:00.600872+00:00 (in 599.993478 seconds)
2016-08-15 21:00:00,611 - WARNING(Thread-42) - The schedule job crashed because of AttributeError("'datetime.timedelta' object has no attribute 'minutes'",)

```

**Comment by juniwang** [comment]
fixed.
see https://github.com/msopentechcn/open-hackathon/pull/653/files
